##
## EPITECH PROJECT, 2020
## Day03
## File description:
## Makefile
##

SRC		=	my_putchar.c		\
			my_strcpy.c			\
			my_strncpy.c		\
			my_revstr.c			\
			my_strstr.c		\

TEST_NAME 	=	unit_tests

test_run:
	gcc -o $(TEST_NAME) $(SRC) tests/*.c -lcriterion --coverage