##
## EPITECH PROJECT, 2020
## Day03
## File description:
## Makefile
##

SRC		=	my_strcat.c	\
			my_strncat.c	\

TEST_NAME 	=	unit_tests

test_run:
	mr_clean
	gcc -o $(TEST_NAME) $(SRC) tests/*.c -lcriterion --coverage