##
## EPITECH PROJECT, 2020
## Day03
## File description:
## Makefile
##

all:
	make -C ./lib/
	make -C ./do_op/

clean:
	make clean -C ./lib/
	make clean -C ./do_op/

fclean:
	make fclean -C ./lib/
	make fclean -C ./do_op/

tests_run:
	make -C lib/
	make tests_run -C ./do_op/

.PHONY: all clean fclean tests_run